version: '3.8'
services:
    phpqa:
      build:
        context: .
        dockerfile: ./Dockerfile
      # image: jakzal/phpqa:alpine
      container_name: phpqa
      volumes:
        - ./project:/project

volumes:
    project:
