version: '3.8'
services:
    phpqa:
      image: jakzal/phpqa:alpine
      container_name: phpqa
      build:
        context: .
        dockerfile: ./Dockerfile
      volumes:
        - ./project:/project

volumes:
    project:
