version: '3.8'
services:
    phpqa:
      build:
        context: .
        dockerfile: ./Dockerfile
      container_name: phpqa
      volumes:
        - ./project:/project
        - ./log:/log

volumes:
    project:
      external: true
    log:
      external: true
